version: '3.7'

services:
  nms:
    image: {{ nms_image }}
    env_file:
      - {{ db_gfs_path }}/env/mysql.env
      - {{ nms_path }}/env/nms.env
{% if keycloak_enabled %}
      - {{ nms_path }}/env/nms_auth.env
{% endif %}
      - {{ nms_path }}/env/time.env
      - {{ nms_path }}/env/nms_custom.env
    volumes:
      - {{ logs_gfs_path }}:/nodelogs
      - {{ nms_path }}/docker_volumes/settings:/app/fbcnms-projects/tgnms/.settings
      - {{ sysdump_gfs_path }}:/app/fbcnms-projects/tgnms/sysdump
    networks:
      - terragraph_net
    command: ["/bin/sh", "-c", "ln -sf $${TZ_FILE} /etc/localtime && until nc -z query_service 8086; do sleep 1; done && cd /app/fbcnms-projects/tgnms && yarn run start:prod"]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  docs:
    image: {{ nms_docs_image }}
    networks:
      - terragraph_net
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  grafana:
    image: grafana/grafana:latest
    env_file:
      - {{ db_gfs_path }}/env/mysql.env
      - {{ nms_path }}/env/grafana.env
    volumes:
      - {{ nms_path }}/grafana/provisioning:/etc/grafana/provisioning
      - {{ nms_path }}/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST={{ db_host }}:3306
      - GF_DATABASE_NAME=$${GRAFANA_DB}
      - GF_USERS_DEFAULT_THEME=light
      - GF_SECURITY_ADMIN_PASSWORD=$${GRAFANA_ADMIN_PASS}
      - GF_DATABASE_USER=$${GRAFANA_MYSQL_WRITER}
      - GF_DATABASE_PASSWORD=$${GRAFANA_MYSQL_WRITER_PASS}
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Editor
    networks:
      - terragraph_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
  terragraph_net:
    external: true
